version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - test.pdf
    - images/*
    - styles/*
    - dist/bundle.js
