version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  build:
    commands:
      - node --version
artifacts:
  files:
    - index.html
    - favicon.ico
    - README.md
    - test.pdf
    - images/*
    - styles/*
