version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre-build:
    commands:
      - echo Starting Pre-build.....
      - npm install
      - npm test
      - echo Completed Pre-build
  build:
    commands:
      - echo Starting Build
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - test.pdf
    - images/*
    - styles/*
    - dist/bundle.js
