version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building
      - node --version
artifacts:
  files:
    - index.html
    - favicon.ico
    - README.md
    - test.pdf
    - images/*
    - styles/*
